name: Build gui

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Install pyinstaller
      run: pip install pyinstaller

    - name: build frontend
      working-directory: ./frontend
      run: npm run build:front

    - name: Build the project for Windows
      working-directory: ./frontend
      if: runner.os == 'Windows'
      run: pyinstaller -F --add-data "snowpack;snowpack" main.py
    
    - name: Build the project for Mac
      working-directory: ./frontend
      if: runner.os == 'macOS'
      run: pyinstaller -F --add-data "snowpack:snowpack" main.py

    - name: Build the project for Linux
      working-directory: ./frontend
      if: runner.os == 'Linux'
      run: pyinstaller -F --add-data "snowpack:snowpack" main.py

    - uses: actions/upload-artifact@v2
      with:
        name: Build ${{ runner.os }}
        path: ./frontend/dist

